global:
  scrape_interval: 15s
scrape_configs:
  # Make Prometheus scrape itself for metrics.
  - job_name: "localhost"
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "cadvisor"
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ["cadvisor:8080"]
